### ISSUE TITLE
Please allow user to input the path to config file when running Hugo deploy

### ISSUE THREAD

**Issue by viraf** [AlbertMorenoDEV/deploy-hugo-to-s3-action#4]
Please allow user to input the path to config file when running Hugo deploy for users using multi config setup with config folder

**Comment by AlbertMorenoDEV** [comment]
sure! let's do it

**Comment by AlbertMorenoDEV** [comment]
Done, try with the last v0.0.6 version

**Comment by viraf** [comment]
Thanks. It works well.
